[theme]
base = "light"
primaryColor = "#1e2d3e"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f5f7fa"
textColor = "#1e2d3e"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
